version: "3.9"

services:
  mongodb:
    container_name: mongo-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    volumes:
      - mongodb-data:/data/db
    networks:
      main:


  mongo-express:
    container_name: mongo_express
    image: mongo-express
    ports:
      - "28081:8081"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    depends_on:
      - mongodb
    networks:
      main:

  telegram_bot:
    container_name: telegram_bot
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    command: "python application/main.py"
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      main:

networks:
  main:
    driver: bridge

volumes:
  mongodb-data: